### ISSUE TITLE
销毁功能失效

### ISSUE THREAD

**Issue by 98Kstar** [ProbiusOfficial/TCL#1]
销毁功能失效了。>>> 3
运行中 ID：ubuntu@*.*.*****
[TencentCloudSDKException] code:InvalidInstanceId.NotFound message:请确认实例ID `['******']`是否存在 requestId:*******,好几次了是这样。要手动上管理平台销毁

**Comment by ProbiusOfficial** [comment]
![image](https://github.com/ProbiusOfficial/Hello_CTF-Shell/assets/41804496/6f109738-2ce7-402a-922f-8f00c34d21f6)
接到过类似问题，请确保：
脚本运行位置有读写条件以便程序能够正常记录示例数据更新json文件。
请确保每次使用逻辑都是正确的，如果因为操作不当导致json文件没有正常更新，请手动fix。
如有疑问请在本issue中继续回复。
